### ISSUE TITLE
can't install R-integration into arcmap

### ISSUE THREAD

**Issue by KelLukas** [R-ArcGIS/r-bridge-install#15] opened 2016-01-24 09:18 UTC
Hey, I think it was already posted here on github, but without any response. So, Im sorry about doble posting, but I have the same issue. 

I have student licence of arcgis 10.3.1 and latest R 3.2.3. I tried to run python scripts through arcmap folder connections but, I can't see any. The only thing I see is the basic structure of r-bridge-install-master, that I have on my desktop ("img", "rtools", "R Integration").

I tried to move this folder elsewhere, run arcmap as administrator, reloading the folder, nothing helped. Are there any ideas how to overcome this behaviour?

Thanks

Lukas

**Comment by scw** [comment] 2016-01-26 18:06
@KelLukas,

I've [added a short video](https://raw.githubusercontent.com/R-ArcGIS/r-bridge-install/master/img/r-install-from-pyt.gif) of installing in 10.3.1 that details the steps. There should be a PYT file, a Python toolbox that contains the tools and is usable from within the Catalog pane. If that doesn't show up, could you post a screenshot of what you're seeing instead?

Thanks,
Shaun

**Comment by KelLukas** [comment] 2016-01-27 14:52
Hello, thank you for your effort. The video is pretty straight forward, as the installation should be. I followed your steps, I even put the extracted folder into downloads (:P) although it shoudn't matter at all. 
Actually, what I have learned through the years with arcgis, for any data analysis and processing, it's always better to put shapefiles into folder which names don't have any diacritics . But that shouldn't be a problem here.

But as again, it doesn't work. When I want to expand the R Intgration .pyt file, it just shows a red cross like there is nothing in there, and the plus sign disappears. I am used to this behaviour with wms servers, not allowing me to connect to them, but a reload or double clicking it always helps.

![arc](https://cloud.githubusercontent.com/assets/16862196/12616961/d96b5a7e-c50d-11e5-8449-dee1fa5f9f92.jpg)
![arc2](https://cloud.githubusercontent.com/assets/16862196/12616968/df77dcc6-c50d-11e5-8235-40f4f3695b05.jpg)


Thanks in advance

Lukas

**Comment by scw** [comment] 2016-01-27 22:02
Lukas,

Thanks for the screenshots and your additional attempts. Yes, historically there were issues with non-ASCII characters in path names, though generally those to work well today. 

From the Catalog View, could you right click on the "R Integration.pyt" toolbox, and select "Check Syntax", and paste or screenshot the message displayed? It looks like a parsing error, my guess is it relates to the metadata files that document the tools, and a installation specific trait that I need to track down.

Thanks,
Shaun

**Comment by KelLukas** [comment] 2016-01-28 06:55
Hello Shaun,
thank you again. Looking at the syntax log, there is actually an acsii error of some kind. Don't know where did it come from :D


![arc](https://cloud.githubusercontent.com/assets/16862196/12637280/3b4f0296-c594-11e5-9e86-c1207d62661d.jpg)

Lukas

**Comment by scw** [comment] 2016-01-28 20:17
Lukas,

Thanks for the screenshot, that helps. It looks like the issue is that when it generates the traceback, it wasn't written to handle non-ASCII characters, but came across an 'é'. I've updated it with a simple fix that should solve the issue, but if it doesn't, I have a more robust fix I can apply instead. Could you retest by downloading the zip file again and trying to open the toolbox? If it fails, could you again show the the error in "Check Syntax"? Thanks!

Cheers,
Shaun

**Comment by KelLukas** [comment] 2016-01-28 22:21
Hello Shaun, 
I am delighted that you take so much of your time to help me. I appreciate it. To be honest, worked like a charm. I just wonder, where did "é" come from. Not that I don't use it, but as I said, not when working with Arcgis :)

![arc](https://cloud.githubusercontent.com/assets/16862196/12660667/2c0b4b38-c615-11e5-991d-703baeace40d.jpg)

Now, is it normal that the "tools" file in catalog doesn't show any tools, while physically there is 10 compiled python files in the folder? Three of them reminds me of the pyt files in R Integration, I don't have any clue about those 7 remaining.

![arc](https://cloud.githubusercontent.com/assets/16862196/12660761/bab831ac-c615-11e5-8918-f4120b2af46f.jpg)


Thank you

Lukas

**Comment by scw** [comment] 2016-01-28 23:04
Hi Lukas,

Great! Yes, where the 'é' is coming from is unclear, it may be a directory name or something else, the full traceback contains a variety of information.

In terms of the additional files: how the Python toolbox stores its metadata for each tool (e.g. the help). You can view this help by opening a tool, then clicking 'Show Help' to get field-by-field help, or clicking 'Tool Help' to get the full documentation. If you uncheck "Hide extensions for known file types" at this location in File Explorer (Tools > Folder Options), you'll see that they are .xml files, and not actually a toolbox:
<img width="386" alt="screen shot 2016-01-28 at 5 26 37 pm" src="https://cloud.githubusercontent.com/assets/1314/12660895/5f63e188-c5e4-11e5-8993-096d2872c7fc.png">

I agree it can be somewhat confusing when looking at the directory. I'll close this issue for now, but let us know if you need any further help linking up R and ArcGIS, and if you haven't already, you can see fully worked examples using the bridge in the [r-sample-tools](https://github.com/R-ArcGIS/r-sample-tools) project.

Cheers,
Shaun

**Closed by scw** 2016-01-28 23:04 UTC
