### ISSUE TITLE
Unable to install R Bindings

### ISSUE THREAD

**Issue by soggypickle** [R-ArcGIS/r-bridge-install#29] opened 2016-08-02 18:55 UTC
I am running ArcMap 10.3 and and R 3.3.1. I download the file, open ArcMap and R.  I go into the toll box and run the tool 'Install R-Bindings.' It errors and i get the following message: Unable to locate R package library. Link failed. How can I locate the R Package library?

The complete line of code is as follows. 
 Executing: InstallBindings false
Start Time: Tue Aug 02 13:52:31 2016
Running script InstallBindings...
Saving URL to 'c:\temp\arc910b\tmpnbu94_\arcgisbinding_1.0.0.122.zip'
Rcmd.exe INSTALL c:\temp\arc910b\tmpnbu94_\arcgisbinding_1.0.0.122.zip
'C:\Users\Username\Documents\R\R-3.3.1\bin\i386'
CMD.EXE was started with the above path as the current directory.
R command returned non-zero exit status.
Unable to locate R package library. Link failed.
Completed script InstallBindings...
Failed to execute (InstallBindings).
Failed at Tue Aug 02 13:52:34 2016 (Elapsed Time: 3.63 seconds)

**Comment by scw** [comment] 2016-08-04 05:42
Hello @soggypickle, sorry to hear the bridge isn't working for you. Could you run the "R Installation Details" script that's included in the toolbox and post it's output? We check the registry for the install location of R, but based on the above it doesn't look like that detection is succeeding.

Thanks, Shaun

**Comment by scw** [comment] 2016-08-05 14:50
@soggypickle that looks like the output of the "Update Bindings" script &mdash; could you try the "R Installation Details" once more? On my machine, this is what it's output looks like:

> Executing: RInstallDetails
> Start Time: Fri Aug 05 10:49:48 2016
> Running script RInstallDetails...
> R (version 3.3.0), installed in: C:\Program Files\R\R-3.3.0
> R packages will be installed into: C:\Program Files\R\R-3.3.0\library
> All R package libraries detected: C:\Program Files\R\R-3.3.0\library
> The ArcGIS R package (version 1.0.0.122) is installed at: C:\Program Files\R\R-3.3.0\library\arcgisbinding
> Completed script RInstallDetails..

**Comment by soggypickle** [comment] 2016-08-05 15:12
Sorry about that! I totally ran the wrong tool!

Executing: RInstallDetails
Start Time: Fri Aug 05 10:11:46 2016
Running script RInstallDetails...
R (version 3.3.1), installed in: \\state.sd.local\Home\GF\gfpr13632\Documents\R\R-3.3.1
R packages will be installed into: \\state.sd.local\Home\GF\gfpr13632\Documents\R\R-3.3.1\library
All R package libraries detected: \\state.sd.local\Home\GF\gfpr13632\Documents\R\R-3.3.1\library
The ArcGIS R package is not installed. Use the 'Install R Bindings' tool to install them.
Completed script RInstallDetails...
Succeeded at Fri Aug 05 10:11:46 2016 (Elapsed Time: 0.01 seconds)

**Comment by scw** [comment] 2016-08-05 18:12
Great, thanks. Interesting, it looks like your installation resides on a network, which from what I've read isn't directly supported by R. If you open R, then type:

```R
R.home()
```
What does it display as the result?

If you'd like to get going now, and rather not wait for us to resolve the install issue when working on a network drive, you can install the package manually within R. To do so, first [download the package](https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.0.122) from GitHub, then follow the steps in [this short screen cast](https://4326.us/R/zipinst/r%20bridge%20install%20from%20zip_player.html) to install from directly within R.

**Comment by soggypickle** [comment] 2016-08-05 20:49
R.home() give the result

` "//state.sd.local/Home/GF/GFPR13632/Documents/R/R-3.3.1"`

**Comment by scw** [comment] 2016-08-08 17:08
Hello @soggypickle,

I can confirm that R does let you install and mostly seems to work fine from a network drive installation. The R Windows FAQ states otherwise, but it looks to be wrong:

[R FAQ, §2.2](https://cran.r-project.org/bin/windows/base/rw-FAQ.html):

> Installing to a network share (a filepath starting with \\machine\...) is not supported: such paths will need to mapped to a network drive.
 
That said, there are issues such as the existing way that we install the package. I've updated the package with an alternate technique for network-based installations, could you download the latest version of the toolbox and try again?

Cheers, Shaun

**Comment by soggypickle** [comment] 2016-08-11 20:33
I did and it has installed successfully. However, when i open R and then library(argisbinding), I am prompted to to run arc.check_product(). I run this command and the i receive this error:

`Error: Could not bind to a valid ArcGIS Pro installation.`

I have an advance ArcGIS Desktop Licence. How can I get R to recognize my licence?

**Comment by scw** [comment] 2016-08-11 20:35
Great! Installation is the hard part. To connect to ArcGIS Desktop, run the R shortcut labeled "R i386 3.3.1". ArcGIS Desktop is a 32-bit application, so it has to talk to the 32-bit version of R.

**Comment by scw** [comment] 2016-09-01 16:59
@soggypickle, I think we've resolved the technical problem with the bridge, so closing this issue. Feel free to reopen it, or open a new one if you're having problems still.

**Closed by scw** 2016-09-01 16:59 UTC

**Comment by JoaoPFS** [comment] 2017-11-16 12:48
I am new at GitHub so hello to everyone!
I am sorry to reopen this issue but I want to try the ArcGIS R bridge but I can't install R Bindings.

ERROR:
"Executing: InstallBindings false 3.4.1
Start Time: Thu Nov 16 12:45:31 2017
Running script InstallBindings...
Updating default R to 3.4.1
Traceback (most recent call last):
  File "<string>", line 233, in execute
  File "C:\Users\João\Desktop\r-bridge-install-master\rtools\install_package.py", line 209, in install_package
    base_path = os.path.join(os.path.abspath(os.path.dirname(__file__)), '..')
  File "C:\Python27\ArcGIS10.4\Lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 9: ordinal not in range(128)
Failed to execute (InstallBindings).
Failed at Thu Nov 16 12:45:31 2017 (Elapsed Time: 0.76 seconds)"

R Installation details:
"Executing: RInstallDetails
Start Time: Thu Nov 16 12:46:53 2017
Running script RInstallDetails...
R (version 3.4.1), installed in: C:\Program Files\R\R-3.4.1
R packages will be installed into: C:\Users\João\Documents\R\win-library\3.4
All R package libraries detected: C:\Users\João\Documents\R\win-library\3.4;C:\Program Files\R\R-3.4.1\library
The ArcGIS R package is not installed. Use the 'Install R Bindings' tool to install it.
Completed script RInstallDetails...
Succeeded at Thu Nov 16 12:46:53 2017 (Elapsed Time: 0.08 seconds)"

Thank you!

João
Windows 10
ArcGIS 10.4
R 3.4.1
